# This theme is based on https://github.com/jekyll/minima
# Please refer above link to know the available configurations

title: ""
# remote_theme: cepdnaclk/eYY-project-theme
remote_theme: jekyll/minima
description: ""
markdown: kramdown

minima:
  skin: dark

kramdown:
  parse_block_html: true
  syntax_highlighter_opts:
    block:
      line_numbers: false
